### ISSUE TITLE
coordinate with web team to integrate with wagtail

### ISSUE THREAD

**Issue by verbalhanglider** [uchicago-library/iiifcollectionbrowse#2]
See [uchicago-library/library-website#79](https://github.com/uchicago-library/library_website/issues/79) for complete TODO list

**Comment by kzadrozny** [comment]
David and I have started a multi-tabbed spreadsheet with considerations as we move forward with integrations: https://docs.google.com/spreadsheets/d/12tCbNDxhcFOGfHpSguOFPhIOFsFVlb3OLlZJK9wUPk4/edit?usp=sharing
## Migration of Current Collections
The Digital Collections tab has an inventory of all the elements each digital collection has. David has found the common threads while also highlighting unique aspects that each collection has. 

## Next Steps
* Emma is going to get the stats and web data on the collection in their current platforms
* Kathy and Tyler are going to assess how much heavy lifting can be done by the iiif manifests and what data should be created in Wagtail
* David is going to write a proposal and migration plan for stakeholders to review

**Comment by kzadrozny** [comment]
Stakeholders approved proposal outline.
@ecboettch Is going to get usage data on the collections (as listed in the "Digital Collections" tab in the spreadsheet linked to above). She will also meet with individual collection stakeholders to discuss required specs.

**Comment by dbietila** [comment]
The project plans for a Wagtail digital collections interface have changed significantly, and this ticket is no longer accurate.
